//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalTCPClient {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniversalTCPClient.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear list ähnelt.
        /// </summary>
        internal static string MainForm_Button_ClearList {
            get {
                return ResourceManager.GetString("MainForm_Button_ClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abort! ähnelt.
        /// </summary>
        internal static string MainForm_Button_Connect_Abort {
            get {
                return ResourceManager.GetString("MainForm_Button_Connect_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect! ähnelt.
        /// </summary>
        internal static string MainForm_Button_Connect_Connect {
            get {
                return ResourceManager.GetString("MainForm_Button_Connect_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnect! ähnelt.
        /// </summary>
        internal static string MainForm_Button_Connect_Disconnect {
            get {
                return ResourceManager.GetString("MainForm_Button_Connect_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan! ähnelt.
        /// </summary>
        internal static string MainForm_Button_Scan {
            get {
                return ResourceManager.GetString("MainForm_Button_Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send! ähnelt.
        /// </summary>
        internal static string MainForm_Button_Send {
            get {
                return ResourceManager.GetString("MainForm_Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AutoClear ähnelt.
        /// </summary>
        internal static string MainForm_CheckBox_AutoClear {
            get {
                return ResourceManager.GetString("MainForm_CheckBox_AutoClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AutoScroll ähnelt.
        /// </summary>
        internal static string MainForm_CheckBox_AutoScroll {
            get {
                return ResourceManager.GetString("MainForm_CheckBox_AutoScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose automatically ähnelt.
        /// </summary>
        internal static string MainForm_ComboBox_Language_Auto {
            get {
                return ResourceManager.GetString("MainForm_ComboBox_Language_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Carriage Return ähnelt.
        /// </summary>
        internal static string MainForm_ComboBox_Lineending_CR {
            get {
                return ResourceManager.GetString("MainForm_ComboBox_Lineending_CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CR + LF ähnelt.
        /// </summary>
        internal static string MainForm_ComboBox_Lineending_CRLF {
            get {
                return ResourceManager.GetString("MainForm_ComboBox_Lineending_CRLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Linefeed ähnelt.
        /// </summary>
        internal static string MainForm_ComboBox_Lineending_LF {
            get {
                return ResourceManager.GetString("MainForm_ComboBox_Lineending_LF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Lineending ähnelt.
        /// </summary>
        internal static string MainForm_ComboBox_Lineending_NoLineEnding {
            get {
                return ResourceManager.GetString("MainForm_ComboBox_Lineending_NoLineEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client ähnelt.
        /// </summary>
        internal static string MainForm_GroupBoxClient {
            get {
                return ResourceManager.GetString("MainForm_GroupBoxClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP scanner ähnelt.
        /// </summary>
        internal static string MainForm_GroupBoxIPScan {
            get {
                return ResourceManager.GetString("MainForm_GroupBoxIPScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Port scanner ähnelt.
        /// </summary>
        internal static string MainForm_GroupBoxPortScan {
            get {
                return ResourceManager.GetString("MainForm_GroupBoxPortScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attempts: ähnelt.
        /// </summary>
        internal static string MainForm_Label_Attempts {
            get {
                return ResourceManager.GetString("MainForm_Label_Attempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Charset: ähnelt.
        /// </summary>
        internal static string MainForm_Label_Charset {
            get {
                return ResourceManager.GetString("MainForm_Label_Charset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Red = Received ähnelt.
        /// </summary>
        internal static string MainForm_Label_Color_Receive {
            get {
                return ResourceManager.GetString("MainForm_Label_Color_Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Green = Sent ähnelt.
        /// </summary>
        internal static string MainForm_Label_Color_Send {
            get {
                return ResourceManager.GetString("MainForm_Label_Color_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Host: ähnelt.
        /// </summary>
        internal static string MainForm_Label_Host {
            get {
                return ResourceManager.GetString("MainForm_Label_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language: ähnelt.
        /// </summary>
        internal static string MainForm_Label_Language {
            get {
                return ResourceManager.GetString("MainForm_Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lineending: ähnelt.
        /// </summary>
        internal static string MainForm_Label_Lineending {
            get {
                return ResourceManager.GetString("MainForm_Label_Lineending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MaxIP: ähnelt.
        /// </summary>
        internal static string MainForm_Label_MaxIP {
            get {
                return ResourceManager.GetString("MainForm_Label_MaxIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MaxPort: ähnelt.
        /// </summary>
        internal static string MainForm_Label_MaxPort {
            get {
                return ResourceManager.GetString("MainForm_Label_MaxPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MinIP: ähnelt.
        /// </summary>
        internal static string MainForm_Label_MinIP {
            get {
                return ResourceManager.GetString("MainForm_Label_MinIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MinPort: ähnelt.
        /// </summary>
        internal static string MainForm_Label_MinPort {
            get {
                return ResourceManager.GetString("MainForm_Label_MinPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Port: ähnelt.
        /// </summary>
        internal static string MainForm_Label_Port {
            get {
                return ResourceManager.GetString("MainForm_Label_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Progress: ähnelt.
        /// </summary>
        internal static string MainForm_Label_Progress {
            get {
                return ResourceManager.GetString("MainForm_Label_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Results: ähnelt.
        /// </summary>
        internal static string MainForm_Label_Results {
            get {
                return ResourceManager.GetString("MainForm_Label_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timeout: ähnelt.
        /// </summary>
        internal static string MainForm_Label_Timeout {
            get {
                return ResourceManager.GetString("MainForm_Label_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string MainForm_ObjectListView_Column_HostName {
            get {
                return ResourceManager.GetString("MainForm_ObjectListView_Column_HostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP ähnelt.
        /// </summary>
        internal static string MainForm_ObjectListView_Column_IP {
            get {
                return ResourceManager.GetString("MainForm_ObjectListView_Column_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Port ähnelt.
        /// </summary>
        internal static string MainForm_ObjectListview_Column_Port {
            get {
                return ResourceManager.GetString("MainForm_ObjectListview_Column_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Done! ähnelt.
        /// </summary>
        internal static string MainForm_ProgressBar_Done {
            get {
                return ResourceManager.GetString("MainForm_ProgressBar_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Universal TCP client ähnelt.
        /// </summary>
        internal static string MainForm_Title {
            get {
                return ResourceManager.GetString("MainForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error! ähnelt.
        /// </summary>
        internal static string MessageBox_Error {
            get {
                return ResourceManager.GetString("MessageBox_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while connecting. ähnelt.
        /// </summary>
        internal static string MessageBox_Error_Connect {
            get {
                return ResourceManager.GetString("MessageBox_Error_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection lost. ähnelt.
        /// </summary>
        internal static string MessageBox_Error_ConnectionLost {
            get {
                return ResourceManager.GetString("MessageBox_Error_ConnectionLost", resourceCulture);
            }
        }
    }
}
